apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  # ip ADDRESS IS ONLY AVAILABLE within the cluster
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP